### ISSUE TITLE
Player Track no longer visible on Dalamud

### ISSUE THREAD

**Issue by sithmaster0** [kalilistic/PlayerTrack#129]
My Player Track hadn't been working since 6.5 dropped. Figured it was a compatibility thing, but I've been seeing it get updates regularly here. Uninstalled it with the intent to reinstall, but when I went to reinstall in Dalamud the plugin just isn't there anymore. No idea how to get it back.

**Comment by kalilistic** [comment]
Hey, PlayerTrack is only available in testing right now. Right before the patch dropped, I released a major update and it only had a few days of testing before the patch. To avoid risking anyone's data, I decided to pull it off stable and keep it testing only for a bit. I think it's almost ready for stable and I hope to push it to stable in the coming days depending on what issues are found.

I'd say if you are comfortable with the chance of needing to restore from a backup, you can enable the testing version (can get help on this in the XIVLauncher Discord if needed). Otherwise, should be back soon.

**Comment by kalilistic** [comment]
Moving PlayerTrack back to stable from testing. Thanks to all the testers. This is a pretty big release and [you can find out the changes and how to get help here.](https://github.com/kalilistic/PlayerTrack/wiki/V3-Changes)
