### ISSUE TITLE
[Request] Use ContentID Everywhere!

### ISSUE THREAD

**Issue by LittleNightmare** [kalilistic/PlayerTrack#165]
i just noticed that acountID and contentID can be get directly from Character.
![image](https://github.com/user-attachments/assets/62fed88a-7dea-40b8-9d0c-4050ea1b4370)
i think it is better to use contentID as primay key for each player. this way it will be easier to track.

PS: could you add a feature to log used name? i find there is a function for log name and world change of player in PlyaerTrack, but looks like only work for local player.

**Comment by kalilistic** [comment]
Hey, with DT I actually already replaced lodestone id lookups with content id. There are still some name lookups as a fallback due to historical data.

I do have a historical name method in IPC but I can update it to include content id.
`public ((string, uint), (string, uint)[])[] GetPlayerNameWorldHistories((string, uint)[] players);`

**Comment by kalilistic** [comment]
Closing as content id is implemented and I don't plan to use account id at this time.
