### ISSUE TITLE
Player in category not removed from current players filter

### ISSUE THREAD

**Issue by kalilistic** [kalilistic/PlayerTrack#27]
If you are set to Current Players...sometimes players in categories will not be removed when they leave. If you switch to another filter and back, they are removed. This doesn't seem to happen consistently so not sure why yet.

**Comment by kalilistic** [comment]
I can't seem to replicate this... let me know if this happens to you and if there are any steps I can follow to force the issue.

**Comment by Lynvae** [comment]
The issue is still present, but I'm not a great tester so I'm not sure what I can do to help you replicate it. I've been having this issue since the major overhaul of the plugin a while back, and it's an issue that happens consistently at all times from the moment the game is launched. Players that aren't assigned to categories do keep updating properly, even while players with categories remain stuck in the window
If you're unable to replicate it, could it have something to do with the size or age of the database?
